# Camera Settings
camera_id: 0
calibration_file: "data/calibration/CalibrationMatrix_college_cpt.npz"

# Model Settings
model: "metric3d" # Options: zoe, midas, metric3d
min_depth: 0.1
max_depth: 10.0
min_brightness: 10
voxel_size: 0.02

# SLAM Settings
frame_interval: 1
orb_features: 5000
feature_match_ratio: 0.75
essential_matrix_threshold: 1.0

# Motion Estimation (Pixhawk)
use_pixhawk: false
motion_distance_threshold: 5.0
motion_rotation_threshold: 0.5

# Segmentation
enable_segmentation: true
nano_segmentation: false
segmentation_model_path: "weights/segmentation/pointnet2_sem_seg.pth"
segmentation_model_name: "src.models.pointnet2_sem_seg"

# Output
output_pcd: "global_map.pcd"
save_point_clouds_only: false
real_time_vis: true

# Dataset Mode
use_dataset: false
dataset_path: ""
